### PR TITLE
PEGS Challenge: update data folder synID

### PR DESCRIPTION
**Pull request by vpchung**
## Changelog
* Update the data folder synID, so that it points to a folder of folders.

---

## Additional Context

This change is needed because for the leaderboard round, "both training (_train.) and validation data (_val.) are mounted in the Docker container under `/input/`."  With our current configuration, only the validation data is mounted.  I have since created a new folder called "leaderboard_data" (synID: syn61464987) and moved the validation data folder and training data folder under it.

I'm not sure yet whether we will need to do a similar update for the test profile -- will check with @gaiaandreoletti once she's back in the office.

### CODE REVIEW

**Review by BryanFauble — APPROVED** [review]

**Comment by jaymedina** [comment]
Looks good! I saw a thumbs up from Gaia in our group chat. Does that mean we can update the test profile too? @vpchung

**Comment by vpchung** [comment]
@jaymedina I haven't confirmed with her yet - sorry!  One sec....

**Comment by vpchung** [comment]
Ah, okay, we can actually close this PR!

After a more thorough discussion with Gaia, it turns out there was confusion between synthetic data and the actual data to be mounted.  I misunderstood and thought the organizers wanted to make this change, but it was more-so a request to look into the participant's question.

So TL;DR - our current synIDs to be mounted are still correct 👍🏼

**Comment by vpchung** [comment]
Nevermind, reopening this....... we will need this change after all 🙃 

For leaderboard round, it will be training + validation
For final round, it will be training + test

**Comment by vpchung** [comment]
For the test profile, I have created a new folder (syn59063539) and have moved the test_data folder under it.  For training, would it work if I did a file link to the training folder that is currently under the leaderboard one (syn61464987)?

@thomasyu888

**Comment by vpchung** [comment]
Or, if it's easier, I can simply move the training folder over to syn59063539 on 7/30 when the final round begins.

**Comment by jaymedina** [comment]
Hi @vpchung, what do you mean by file link? And when you say "for training", do you mean for the first round (validation round)?

**Comment by vpchung** [comment]
Ah sorry, I should've been more clear.  So for the leaderboard round (which uses the `pegs_challenge_validate` profile), the data that should be mounted is:

* training data (syn59063538)
* validation data (syn59063540)

These are now located under a new folder called "leaderboard_round" (syn61464987).

For the final round (which uses the `pegs_challenge_test`profile), the data that should be mounted is:

* training data (syn59063538)
* test data (syn59063539)

I created a new folder called "final_round" (syn61485785) and have moved the test data under it.  Since the training data is currently located in the "leaderboard_round" folder and I didn't want to create a copy, I was wondering if I could do a file link instead:
Screenshot 2024-06-26 at 2 38 35 PM

**Comment by jaymedina** [comment]
Oh I see - Let's test this out! Would you mind doing the file link and I'll recreate [what the workflow does to retrieve and stage the data](https://github.com/Sage-Bionetworks-Workflows/nf-synapse-challenge/blob/b477e3a72cdb374ebeba8ad183d1b329aa803d09/modules/synapse_stage.nf#L18) and see if the test folder shows up.

**Comment by vpchung** [comment]
OK done!

Screenshot 2024-06-26 at 3 01 46 PM

**Comment by jaymedina** [comment]
Hi @vpchung , it looks like a file link won't work with the `synapse get -r` command, therefore the staging process in `model2data` won't work the way we want:

image

If we're pressed for time, I think the fastest and easiest approach would be to either copy the `train_data` over to `final_round` or, as you suggested move it over to `final_round` before that round opens up. I'll bring this up to the team (re: adding a feature to download through a final link using a simple `synapse get` command on SynPy)

**Comment by vpchung** [comment]
bahaha, darn - it was worth a shot.  Thanks for trying anyway!

**Comment by jaymedina** [comment]
For now we'll go with your suggestion of moving `test_data` subfolder to `final_round` before the final round starts. I'll add a Jira ticket to have `data_folder_id` support multiple synIDs, so we can feed it the subfolders directly, instead of the folders that house the train/test/val subfolders. This should make `model2data` more customizable for you.

Until then, this is ready to merge! I'll update the DAG and request a validation before pushing it to `prod`

**Review by jaymedina — APPROVED** [review]

**Pull request merged**
